### PR TITLE
Update 'get_git_version.bat' to generate 'git_version.inc'

### PR DESCRIPTION
**Pull request by jantoreh**
Proposed solution to avoid using 'VersionScript' to generate 'git_version.inc'. This eliminates the need for 'VersionScript.exe'. Found to be working well.

### CODE REVIEW

**Comment by davidovitch** [comment]
@jantoreh thanks for these PR's! We'll have a look at them very soon!

**Comment by jantoreh** [comment]
Great! I see that all commits ended up here, but only no. ddaf48 was ment for this specific PR. The others either have their own PR, unless they are changes specific for my own use.

**Comment by fzahle** [comment]
in that case you need to close this PR and make a new branch from the master branch and then cherry-pick that specific commit from your patch-5 branch.

**Comment by fzahle** [comment]
also, in my experience its not a good idea to make commits to your own master branch since this is now diverged from the origin's master.  don't know whether there's a neat way to clean up your own master, but otherwise I'd delete your fork, fork again, and then re-push whatever branches you want to keep form your local checkout. just a suggestion.

**Comment by jantoreh** [comment]
Ok, thanks. I will clean up and delete this request shortly.

**Comment by jantoreh** [comment]
New PRs are made. Will not make my own branch until you have considered them.

**Pull request closed without merging**
