### PR TITLE
Bug Fix: path in git version script

### PR DESCRIPTION
**Pull request by jantoreh**

### CODE REVIEW

**Comment by davidovitch** [comment]
This is peculiar, in my Visual Studio 2010 setup the base path is defined as ```src/dtu_we_controller``` because ```src/get_git_version.bat``` is called in a pre-build step for this project. Since ```src/get_git_version.bat``` starts with moving one directory upwards, we end up in the ``src`` directory. This works fine on my system with Visual Studio 2010. How are you compiling the project, and why is it different for your setup? (note that I am not exactly a Visual Studio expert).

**Comment by jantoreh** [comment]
I am compiling with Make in both Linux and Windows. It makes sense if the `get_git_version.bat` file is executed in the `src/dtu_we_controller` folder. I was testing by executing the .bat file with a double-clck in Windows, which requires the propsed change to work. But if it works in VS, I can manage with the current setup.

**Comment by davidovitch** [comment]
Shouldn't we make sure that the whole setup works for both the makefile and the Visual Studio solution file, and on both Windows and Linux? I welcome any MR to that end, and I don't mind changing the Visual Studio solution file if that means we have a more elegant makefile and/or Linux build procedure.

**Comment by jantoreh** [comment]
Agree. I will let you know if I should find a working solution.

**Pull request closed without merging**
